include: package:pedantic/analysis_options.yaml
analyzer:
  exclude:
    - lib/generated/**
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations